### ISSUE TITLE
Sinh numerical issue for small inputs

### ISSUE THREAD

**Issue by jackschmidt** [infusion/Complex.js#27]
Sinh gives incorrect results for small inputs. For example, `sinh(1e-17) == 0` but `Math.sinh(1e-17)==1e-17` (which is correct). I suggest the following fix:
```js
  // Accurate and fast
  var sinh = Math.sinh || function(x) {
    return ( Math.abs(x) < 1e-9 ) ? x : ( (Math.exp(x) - Math.exp(-x)) * 0.5 );
  };
```

**Description of the issue:**

The current implementation
```js
  // Current code
  var sinh = function(x) {
    return (Math.exp(x) - Math.exp(-x)) * 0.5;
  };
```
has trouble with |x| small. Since Math.sinh is in most javascript engines, it'd make sense to have something more like
```js
  // Accurate and fast on modern browsers, old behavior in IE
  var sinh = Math.sinh || function(x) {
    return (Math.exp(x) - Math.exp(-x)) * 0.5;
  };
```
or if one wants accurate results in IE use the taylor series expansion:
```js
  // Accurate everywhere, fast on modern, fairly fast on IE
  var sinh = Math.sinh || function(x) {
    return ( Math.abs(x) < 1e-9 ) ? x : ( (Math.exp(x) - Math.exp(-x)) * 0.5 );
  };
```

**Proof of convergence:**

First lemma (Taylor): If `f` is three-times differentiable on an interval `[a,b]`, then
```
f(b) = f(a) + f'(a)*(b-a) + f''(a)*((b-a)**2)/2 + f'''(c)*((b-a)**3)/6
```
for some `c` in `(a,b)`. 

Second lemma (IEEE): If `A` is exactly represented in Float64, and
```
|B| < 2**(-53)*|A|
```
then both `A` and `A+B` have exactly the same Float64 bit representation.

*Proof:*
Take `f(x) = sinh(x)`, `a=0`. Then `sinh(b) = 0 + b + 0*b**2/2 + cosh(c)*b**3/6`. In other words, `sinh(b) - b = cosh(c)*b**3/6` for some `0 < c < b`. Since `f'''(c) = cosh(c)` has its maximum absolute value on `[0,b]` at `c=b`, the maximum value of `|sinh(b) - b|` is strictly less than `cosh(b)*b**3/6`. In order to ensure that, as floating point numbers, `b = b + cosh(c)*c**3/6`, we need that `cosh(b)*b**3/6 < b * 2**(-53)`, or equivalently that `cosh(b) * b**2 < 6 * 2**(-53)`. This is true for `b < 1e-8`.

The constant used above is 1e-9 to match glibc's slightly inaccurate implementation (which is correct to all displayed decimal places, but gets one bit wrong when x=1e-8). Maple, julia, mpfr, and gcc (when it sees constant expressions) get it correct. Glibc (so when gcc doesn't see the expression as constant), octave, Matlab R2015, Firefox, Chrome, Node, etc. are one bit off.

**Comment by infusion** [comment]
That's a nice bug report, even with proof of convergence. Do you know if modern JS engines do this right or should we rely on an own implementation exclusively?

**Comment by jackschmidt** [comment]
I think (but am no expert) that modern JS engines' `Math.sinh` all have about the same accuracy, so all but the last bit or two is correct (which is often allowed to be incorrect for efficiency).

The `Math.sinh || function(x) {` is intended to use the Math object's implementation if available, and only switch to (x or (e^x - e^(-x))/2) if Math.sinh is unavailable.

I think each JS engine is likely to be using the OS supplied numerical library, so there is likely to be a lot of similarity across the board.

https://www.gnu.org/software/libc/manual/html_node/Errors-in-Math-Functions.html#Errors-in-Math-Functions mentions this "fairly correct answers" standard. Usually 0, 1, or 2 bits can be incorrect, but I saw some functions with up to 7 bits incorrect on some architectures. On MacOS X and most Linux, I suspect most JS engines will be asking GLibc to compute the answer.

I don't have easy access to Windows computers for testing, but the documentation:
https://docs.microsoft.com/en-us/cpp/c-runtime-library/floating-point-support
suggests that Visual Studio is similar, one bit is often wrong, but larger errors should be unusual.

MPFR is nice in that it computes all bits correctly (often by computing more bits which are discarded). GCC uses it for constant expressions, and some math software uses it as well.

**Comment by gwhitney** [comment]
mathjs works fine with the native implementation. I would only use Jack Smith's suggestion so that something reasonable will happen on those browsers that don't have a native implementation of sinh. If all browsers did, I would simply suggest always using Math.sinh.
The cosh values look fine so far as I've noticed either way, but I agree the implementations should be symmetric, and I wouldn't be astonished if the straightforward implementation of cosh had numerical issues elsewhere in its domain. Though perhaps it doesn't, as subtraction may be more fraught than addition.

**Comment by infusion** [comment]
Sorry for the stall issue here. I fixed it and a new release is made to npm

**Comment by gwhitney** [comment]
No worries! Thanks for the fix. I've pushed a PR to mathjs adopting complex.js@2.1.1 and it seems to do the trick with sin(a+bi) for small b. (However unfortunately there's still one case of our new lgamma(z) that is pretty inaccurate, we'll let you know if that happens to track back to complex.js, but at the moment I have no idea.) Thanks again!

**Comment by donhatch** [comment]
If I understand correctly, the "proof of convergence" proves that x is a good answer when |x| < 1e-9.
I buy that, but outside that range, the new function isn't very good!  Here, you can see in gnuplot, near the switch point 1e-9, the error is about 5e-17, i.e. the relative error is about 5e-17/1e-9 = 5e-8, i.e. roughly single-precision accuracy, which isn't very good.

$ gnuplot
gnuplot> not_very_good_sinh(x) = abs(x)<1e-9 ? x : (exp(x)-exp(-x))*.5
gnuplot> set samples 1001
gnuplot> plot [-1e-15:1e-15] plot [-1e-15:1e-15] sinh(1e-9+x)-1e-9, not_very_good_sinh(1e-9+x)-1e-9

![image](https://github.com/infusion/Complex.js/assets/12412901/8a3758d1-97ad-456b-ad1a-efff3f392bc8)

There's a high-quality implementation of sinh, in terms of expm1, on this old page of mine: https://www.plunk.org/~hatch/rightway.html
In javascript, it would look something like this:
```
var u = Math.expm1(x);
return .5 * u / (u+1.) * (u+2.);
```

**Comment by donhatch** [comment]
Also, the fix https://github.com/infusion/Complex.js/commit/d995ca105e8adef4c38d0ace50643daf84e0dd1c includes the following new implementation of cosh:
```
var cosh = Math.cosh || function(x) {
  return Math.abs(x) < 1e-9 ? 1 - x : (Math.exp(x) + Math.exp(-x)) * 0.5;
};
```
This doesn't look right to me at all:
- near x=0, cosh(x) is approximately 1+x^2/2, not 1-x
- and I don't think the threshold 1e-9 makes any sense for that (you could, however, say `if (abs(x) < 1e-8) return 1;` if you wanted, I guess, but this is going off on an unnecessary tangent).

Actually, I don't think any threshold is needed for cosh at all-- can't you just `return (Math.exp(x) + Math.exp(-x)) * 0.5` regardless of the value of x?  There isn't any catestrophic cancellation problem here, as far as I can see.

**Comment by gwhitney** [comment]
These are some excellent points. Indeed, the Taylor series for cosh(x) at 0 is 1+x²/2.  And I agree that when abs(x) is less than 1e-8 (or 1e-9 for that matter) it makes no sense to add x²/2 to 1; it won't change the floating-point value of 1, as it will be too small in comparison.

In the vein of better Taylor series, would an alternate way to fix the issue for sinh(x) near |x| = 1e-9 be to use one more term from its Taylor expansion, i.e.  use x + x³/6 instead of just x as the expression near 0? And I agree, I should likely have expressed the idea more strongly above that there was not necessarily any reason to use a similar case structure for cosh, since addition does not have the problem of killing precision that subtraction does.

But stepping back a bit, these bits of code only come into play if there is no JavaScript-native Math.sinh and Math.cosh present. In 2024, they are firmly part of the JavaScript standard, and well-implemented on at least the top 4 browsers (Chrome, Safari, Edge, and Firefox) which account for 99% of all browser usage, if I understand correctly. (You didn't actually observe bad behavior of this package in practice, did you @donhatch? Perhaps, since the "backup" implementations have remained flawed, it's best just to require that Math.sinh and Math.cosh be present and simply rely on them?  If you prefer to continue having backup implementations, @infusion, then I agree another round of fixes to them is in order.

**Comment by donhatch** [comment]
@gwhitney wrote:
> In the vein of better Taylor series, would an alternate way to fix the issue for sinh(x) near |x| = 1e-9 be to use one more term from its Taylor expansion, i.e. use x + x³/6 instead of just x as the expression near 0?

And use a larger threshold?  I don't know, but I suspect you'll still get unnecessarily poor accuracy just outside the new threshold.  Then if you add yet another term and raise the threshold further, the same thing will happen, and at the end of this road you'll end up just implementing a full Taylor expansion, which doesn't sound like fun... the alternative implementation in terms of expm1 is solid and easier.

>  (You didn't actually observe bad behavior of this package in practice, did you @donhatch?)

Correct, I didn't.

I agree that this might be a good time to just get rid of these backup implementations and just require Math.sinh and Math.cosh to be present.

**Comment by gwhitney** [comment]
> > In the vein of better Taylor series, would an alternate way to fix the issue for sinh(x) near |x| = 1e-9 be to use one more term from its Taylor expansion, i.e. use x + x³/6 instead of just x as the expression near 0?

> And use a larger threshold? I don't know, but I suspect you'll still get unnecessarily poor accuracy just outside the new threshold.

Well, there must be some magnitude above which the direct computation from the definition (e^x - e^{-x})/2 works fine for doubles. So you only need enough Taylor series to work well up to that magnitude. But I agree that this point is moot if @infusion decides to just require Math.sinh and Math.cosh.

**Comment by infusion** [comment]
Hey, thanks for bringing this up! I agree that in practice this shouldn't cause any problem since most engines have native sinh/cosh support these days. I started fraction.js and complex.js about 10 years ago when polyfills were necessary but at that time it was probably too rare that people used those functions. It's fun that I still remember the moment I entered `1-x`, having been too lazy at that moment to do the Taylor expansion again and obviously failed at it. And I also agree that the threshold is meaningless and the condition is not necessary.
What do you guys think, should we fix the backup or get rid of it?
https://www.plunk.org/~hatch/rightway.html << this is pretty nice, thanks!

**Comment by gwhitney** [comment]
Since you asked, if it were up to me I would switch to an assertion at startup time that Math.sinh and Math.cosh are present, failing altogether with some intelligible message if they're not, and then rely on them. No real point in reinventing this particular wheel, especially since it has so many potential ways to go flat...
